add certs branch
Congyuwang/quicnet pull request #2
Opened 2023-08-25 13:00 UTC by JiangDonglai98

2023-08-25 13:10 UTC, Congyuwang requested changes
根据上几个comment修改

2023-08-25 13:10 UTC, Congyuwang commented on .gitignore
> +/certs
末行回车

2023-08-25 13:10 UTC, Congyuwang commented on .gitignore
> +/certs
见https://unix.stackexchange.com/questions/18743/whats-the-point-in-adding-a-new-line-to-the-end-of-a-file

2023-08-25 13:10 UTC, Congyuwang commented on gen-certs.sh
> +echo "构建：$certsNum 组证书"
echo输出改英文

2023-08-25 13:10 UTC, Congyuwang commented on gen-certs.sh
> +echo "构建：$certsNum 组证书"
后面同理

2023-08-25 13:19 UTC, JiangDonglai98 commented on gen-certs.sh
> +echo "构建：$certsNum 组证书"
finished

2023-08-25 13:37 UTC, Congyuwang requested changes
After some thought, I think we should modify the script design a little bit.

The current design is: `./gen-certs.sh <certsNum>`. And it will generate `direct-node-{0..certsNum}`. This is no good for customized nodes name.

I suggest changing the API to: `./gen-certs.sh <certName1> <certName2> ...` to generate certs for any number of certificates.

If you find shell script inconvenient for this task, you may use `python`.

2023-08-25 13:37 UTC, Congyuwang commented on gen-certs.sh
> +# 使用循环创建文件夹并在其中生成文件
comment 用英文

2023-08-25 13:37 UTC, Congyuwang commented on gen-certs.sh
> +#cd /root
删除所有comment掉的代码

2023-08-25 13:40 UTC, Congyuwang commented
If you decide to use python, you may even try to validate if the domain names:
- no duplicate domain names
- domain names follows standard domain name regex

2023-08-25 14:17 UTC, JiangDonglai98 commented on gen-certs.sh
> +#cd /root
add standard domain checking and duplicate checking

2023-08-26 03:46 UTC, Congyuwang approved these changes
很棒

2023-08-26 03:47 UTC, merged